WIP WIP WIP

diff --git a/zsh/zshenv b/zsh/zshenv
--- a/zsh/zshenv
+++ b/zsh/zshenv
@@ -21,6 +21,29 @@ screenshot() {
   grim -g "$(slurp)" "$HOME/Pictures/Screenshots/screenshot-$date.png" && paplay "$HOME/dotfiles/audio/screenshot.wav"
 }
 
+switch_bombadil_profile() {
+  # Allow switching profiles using the wofi launcher/menu program (https://hg.sr.ht/~scoopta/wofi).
+
+  if ! command -v bombadil &> /dev/null; then
+      echo "bombadil could not be found" >&2
+      exit 1
+  fi
+
+  if ! command -v wofi &> /dev/null; then
+      echo "wofi could not be found" >&2
+      exit 1
+  fi
+
+  SELECTED_PROFILE=$(bombadil get profiles | wofi -i -d -p "Switch Toml Bombadil Profile:")
+
+  if [ "$SELECTED_PROFILE" = "default" ]; then
+      bombadil link
+  else
+      bombadil link -p "$SELECTED_PROFILE"
+  fi
+
+}
+
 wob_volume() {
     volume=$(pacmd list-sinks|grep -A 15 '* index'| awk '/volume: front/{ print $5 }' | sed 's/[%|,]//g')
     if [ "$volume" -gt 100 ]; 
